---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBfEaEMtdlA501WJPz0bf+owPo3CAHjaBKbjVw3SSU+5mdWKXgtG14G6IxcrFeR+BPaUiP7CMX9Mw0QFrnUUSI/5hY3iVcmT45VC7xnFqgDpDuzpDqUCGAWIYN3ncL9JS4f/4cEcbBcqYoatQ6DeBEZ3rkUllL3sWXB9B9FzJ4vOV02Q+ckd8qSkBpUejhawlMSC6wCEIRYVCdrb9Vpx+dOMGEq6csKR0eftYSJIvPD6GMKvZzSJxPq8R1JhtdiAM4WJt04KXHIoVLD07cPJQexiXDVbd8+4RZz+YKMAtY95ZruusJH5/mqpu7AGq/Y799Ui1d4igAr+YdESXIml+1gSdL0QPiqXMXRE9WTklWMtKjxHnkJDS3VhS7YQ8zawY4GvkqOK7jd5FJvJPmhby0O8okfgebosYFCZrO0hbekxE0oVAvFv2NJFnDk6NYyZUIcwjNn+wRB26MkLZfAWqsFU3a8PUKCBHFzUZDshkWzdhqanpgKCKyUIEI3cqogwoH/yBPUuZj2S4sK4Tov7nlqHOXowZSXvMbxUoFlT6HR5l4PNb/eyzodlBDnkf9dxQ1dynRG0xPOy50XNwBCF7Spso8b4qYtzfg3v7qZTlLxCFeCRYSIXL7iCaS+bNaDjuJscz+jkTkyjyXhLiKGG6MRY4L7C6RrpaiKLTsr/WzbObJtctCDeYZKWpc7NkIKlDEc5iZ0Zhei1FCo
    MINIO_ROOT_USER: AgAHQKhpHZZzvt1QTDZzez+JM13A8ELgRV2Jc4fVlTz79cUvapi/DYRLpHBMMKY4329eOF72V5l86PB6DovjI/iCCp43no1bj7TomkFNnEoS3C0+vJGJX8/WDa9U++VeXcduIuk6Mi3Fruqk1GeRUtPgrZK8HQfLPvAGzIJ34zGor67wOUc+mDNFY3pKzFiemQ65H9fvHArpVcHcTxzLb0FV9GRpSWgPmp+h68vlhrGOov02LTHE62+n0wdrm1RrtWw88ACy/m4A4Fr6r0PTsncJ+BbE5O9r1Ad+nU3aYRHk/uAPURq1IzyWsVR44Tz57WuQnWKaJBpwPHx2thxhTpvyTGG4UvQhNlNFCoo8sr1zvIS8WlCvZ3WqWF7KcF46ShmmAmBQwoYNvtjeiOItnwihuFnwDaV+XOhXD9XJKB5JLCvFVO4T62YBKL2gDHZtpuCYkRJ/WTB/GIH8mrmJBFvPKk4h+eqGpE3fuucSEvsVoBleFkvUsF2lDPWTTy7pTEZgrlBJ9ZshVvLNm8TsOnrphRYtepTBsmjAg468d+IBuuqFJ0NSBs5vdo99BEaZWfK315RYR526YAZtWcZ2JNIe6ZStQ+qdkSlq+fSEFh+k/E+QbMViI0dwq3mAI/r/ClC2hWYtl28b0vVzE0UVTn0oGyDcXAxF2VQyi6fWii2ZjKvdUXdTR1tQcGjKA3ybXDuMYNA0jw==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
