---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBYH9DIEIHCgMjbzGd1ux3BzvE4Z9lI8Dz9v7bW3udG/T/+HxDO6S7LhxqquewRt9yB7WZ9oylQ3LL7806zlRqVEUB7RsifvUXVs2S4xIMqzSgaw3rr8pYeOX+rRDJ3SyDXtcjEOKEkCjap7FwJlAVhGsxWCYg5fXXwpn1CuuKadpkdx4Sa/nJi9u2NS4279Ls2qDqQBaqUYEV/vNTmy+IkPQAV2Lw/ucRnA09z9jDt0MN5codMGtnzgJTRAvZWCoe2Ek42+OhA2gGXUoFtfhHuLTzCYzIzeMst7Bp3ZnEhgHeTB305obWES2StskvNifMmZK/NqGrUrEbbTELeu8YLvRpRorCDwQe/JRlDEntkrry4jkvQENe+HPhgZHMNJfZFuKNM5/ZQEpIiuglHXZpdWlZpdfC+/5taGczMF6d1CHQ77v6n8uzf9wnPjOE/HQAVWbTvuc1rKJbI8nD4cXVl736r//qVj75hP/gINmBUNxYHcSB+sq/crjEjCEWSAQzCOpjzLjJpVGagcseiJMQGJObSBLqOchFejkDVnj0OHH/DRL/LHy1ppw2OEQueaZlG9Y4GdKqjOCMU1zO4TJhDZXL5ifUNP6DP9ZBkOBUTZEq3ZHGOs6rrSZycwKpxxiBmJLAQj0fg0aD1zjPrJHKOvqNd6lE81O8r0wZn8jAPY00mWVP7Zvtb8zjHG9dgskc767kwXQ==
    MINIO_ROOT_USER: AgAz7g346hgMWWDyzPq0qa5jwL5fnlGchiqtSPu40onrevg78OTQZNts+NbMZyzQd+rgYaWFJycYztj1CEiJl0o5cYY0HcSdhSoTLdevcXwAa9BPJveC5z/ofHcVwJra4Vu/7GhnwRv1mQmot9rp8NJ1Wiyl1o7FxmcMVX6IT/4/8VGo9lIdWkJiDWd+FJ9r8cfPqAgDLpIexCwjg0zOm5zKEIG5xwnjaaQM/RO9WH/JWM0moHBo3bJ0gO9EbFgF+b4zY6074OJUSlcXCa7xn68lUWyzl3gwSjZK8z4YxKfy27gRuaJC4/dcElbftBz8fsmtkJCcuYpLcrrtlIQKYBY82l6XMOiXL+H6yXjfgpL2SF2+72UMz6ok8HKEGUyMYniELOzfU1KQIlHyNFDgfay9V2pofQ4SOGCyAjnlAfpzf6tBHAeWtuw6OhhrsT2v9jWYW2QR4YNqLc/N/l18lYAWCOsfMbGESm0PcZQWgYJVEEcrv2fw7TbtpJ2o1SeEBUQFFkQgyy9lvNC3ajVsD+jE0I8p4opLZVWBo/TfQiIxsm8Erlbr/WbgYImWxX5JmGGkTxZ7g8HZkk1rUPuc5yMQMYtRckCc0h8z/oU+rS3m3E9Ns4C7paAzx6VxyRLSkhEkNQoZtBdXQRFkD9/SkSpOfSI0D1hspjI1MzkP2FAgBl7mZXqIakAcpMqhRNGhBLjmCRC/wg==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
