apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-db-pvc
  namespace: airflow
  labels:
    app.kubernetes.io/name: airflow-db
    app.kubernetes.io/part-of: anime-lakehouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
