apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/part-of: anime-lakehouse
spec:
  project: default
  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: "1.16.0"
      helm:
        valueFiles:
          - $values/infra/kubernetes/base/airflow/values.yaml
    - repoURL: https://github.com/luizcontri/anime-lakehouse.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
